#!/bin/bash
﻿
#BSUB -W 12:00
#BSUB -o /rsrch3/home/radphys_rsch/jdecunha/SuperTrackValidation/run_logfiles
#BSUB -cwd /rsrch3/home/radphys_rsch/jdecunha/SuperTrackValidation/runFiles
#BSUB -q medium
#BSUB -M 165
#BSUB -R rusage[mem=165]
#BSUB -n 28
#BSUB -u jdecunha@mdanderson.org
#BSUB -J proton_10MeV_1nm

source /rsrch3/home/radphys_rsch/jdecunha/configure.sh

../build/SuperTrackValidation -mac ../macros/proton_10.0MeV_1nm.mac -seed $( shuf -i 1-2000000000 -n 1 ) -mt NMAX 

