#!/bin/bash
﻿
#BSUB -W 24:00
#BSUB -o /rsrch3/home/radphys_rsch/jdecunha/SuperTrackValidation/run_logfiles
#BSUB -cwd /rsrch3/home/radphys_rsch/jdecunha/SuperTrackValidation/runFiles
#BSUB -q long
#BSUB -M 165
#BSUB -R rusage[mem=165]
#BSUB -n 28
#BSUB -u jdecunha@mdanderson.org
#BSUB -J proton_polyenergetic_3_1um

source /rsrch3/home/radphys_rsch/jdecunha/configure.sh

../build/SuperTrackValidation -mac ../macros/proton_polyenergetic_3_1um.mac -seed $( shuf -i 1-2000000000 -n 1 ) -mt NMAX 

